### ISSUE TITLE
Missing helper functions

### ISSUE THREAD

**Issue by ottj** [AndreaCossu/ContinualLearning-SequentialProcessing#1]
Thanks for releasing the code for this interesting paper.
I tried to run the code, but it seems that multiple helper function are missing, e.g. in the mnist experiment:
write_test_results(...)
write_intermediate_test_results(...)
save_autoencoders(...)
etc.

**Comment by AndreaCossu** [comment]
I apparently added the wrong `tasks/utils.py`, which had basically the same content of `tasks/audioset/utils.py`. Sorry about that.
Now I pushed the correct version.
If something is still missing, please let me know.

**Comment by ottj** [comment]
Thanks for the quick response. 
Yes, now it works. Issue can be closed.
