### ISSUE TITLE
DataLoader Error

### ISSUE THREAD

**Issue by rkarn** [AndreaCossu/ContinualLearning-SequentialProcessing#2]
python mnist.py generates following issue:

Traceback (most recent call last):
  File "mnist.py", line 289, in <module>
    loader_task_test = DataLoader(mnist_dataset_test, batch_size=args.batch_size, shuffle=False, drop_last=True)

Remedy:
Add following line in mnist.py
from torch.utils.data import DataLoader

**Comment by AndreaCossu** [comment]
thanks for reporting, this is now fixed :smile:
